
spring.application.name=jwtApplication

spring.datasource.url=jdbc:postgresql://localhost:5432/jwt_local_db
spring.datasource.username=postgres
spring.datasource.password=admin
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true


# Enable Flyway
spring.flyway.enabled=true

# Flyway migration location
spring.flyway.locations=classpath:db/migration

# Validate migrations when application starts
spring.flyway.validate-on-migrate=true

# Don't allow Flyway to clean/delete database
spring.flyway.clean-disabled=true


# =====================================================
# SERVER
# =====================================================

server.port=8080

jwt.secret=VGhpc0lzQVN1ZmZpY2llbnRseUxvbmdTZWNyZXRLZXlGb3JKV1Q=
jwt.expiration=300000

spring.security.user.name=admin
spring.security.user.password=admin

